modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="metrolasttunnel"
version="0.3.0"
displayName="Metro: Last Tunnel"
authors="David"
description='''Аптечка для Minecraft 1.20.1 Forge. Использование восстанавливает 3 сердца здоровья.'''

[[dependencies.metrolasttunnel]]
modId="forge"
mandatory=true
versionRange="[47.0,48.0)"
ordering="NONE"
side="BOTH"

[[dependencies.metrolasttunnel]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
